### PR TITLE
feat: Add support for react 18

### PR DESCRIPTION
**Pull request by ronnyroeller**

### CODE REVIEW

**Review by thilohaas — APPROVED** [review]

**Review by EriCreator — APPROVED** [review]
merge asap

**Comment by EriCreator** [comment]
@matthewp can you take a look at this please?

**Comment by matthewp** [comment]
Sorry for the delay on this. react-robot is being moved to the Robot monorepo where it will be better maintained. Upgrading to React 18 there, see https://github.com/matthewp/robot/pull/191

**Comment by matthewp** [comment]
This has been released!

**Pull request closed without merging**
